version: '3.4'
services:
  netbox:
    ports:
      - 8000:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netbox.rule=Host(`netbox.lroland.fr`)"
      - "traefik.http.routers.netbox.entrypoints=http"
      - "traefik.http.services.netbox.loadbalancer.server.port=8080"
        # TLS
      - "traefik.http.routers.netboxs.rule=Host(`netbox.lroland.fr`)"
      - "traefik.http.routers.netboxs.entrypoints=https"
      - "traefik.http.routers.netboxs.tls.certresolver=lroland"
      - "traefik.http.routers.netbox.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
    networks:
      - oueb
