version: '3.7'
services:
  traefik:
    image: traefik:v2.0
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/traefik.toml:/traefik.toml
      - ./conf/acme.json:/acme.json
      - ./conf/rules.toml:/rules.toml
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.lroland.fr`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=lroland"
      - "traefik.http.middlewares.auth.basicauth.users=louis:$$apr1$$hL7R6q.E$$zhA1O2iyH6MWR6ZRpX1CU."

      #- "traefik.http.routers.md.entrypoints=https"
      #- "traefik.http.routers.md.rule=Host(`codimd.lroland.fr`)"
      #- "traefik.http.routers.md.service=md@file"
      #- "traefik.http.routers.md.tls=true"
      #- "traefik.http.routers.md.tls.certresolver=lroland"

     # - "traefik.http.routers.netbox.entrypoints=https"
     # - "traefik.http.routers.netbox.rule=Host(`netbox.lroland.fr`)"
     # - "traefik.http.routers.netbox.service=netbox@file"
     # - "traefik.http.routers.netbox.tls=true"
     # - "traefik.http.routers.netbox.tls.certresolver=lroland"
      
    networks:
      - oueb
      - default
    
  my-app:
    image: containous/whoami:v1.3.0
    labels:
      - "traefik.http.routers.whoami-http.entrypoints=http"
      - "traefik.http.routers.whoami-http.rule=Host(`who.lroland.fr`)"
      - "traefik.http.routers.whoami-http.middlewares=whoami-https"
      - "traefik.http.middlewares.whoami-https.redirectscheme.scheme=https"
      - "traefik.http.routers.whoami.entrypoints=https"
      - "traefik.http.routers.whoami.rule=Host(`who.lroland.fr`)"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=lroland"


networks:
  oueb:
    external: true
  default:
      driver: bridge